name: main CI

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'Makefile'
      - 'CMakeLists.txt'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
